version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  flask:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on: 
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/HospitalDB

networks:
  default:
    external:
      name: proxy
